### ISSUE TITLE
No link

### ISSUE THREAD

**Issue by Jiwoo-BongHee** [shinonome-cafe/weeb-sh.ts#1]
Hi, 
I'm coding a discord bot in JS, so I created a commad for hug image : 
```javascript
if (message.content.startsWith("hug")){
        var hug = weebSh.getRandom({
            type: "hug",
            tags: "girl",
            nsfw: "false",
        })
        message.reply(hug)
    }
``` 
But the bot send nothing.

**Comment by hsiW** [comment]
You need access to the Weeb.sh api to be able to use this lib, which I checked and it seems you currently do not have.
